### ISSUE TITLE
createStore返回的store，使用reduxStore的方法时，类型有丢失

### ISSUE THREAD

**Issue by Juliiii** [modern-js-dev/reduck#99]
RT

**Comment by xuchaobei** [comment]
类型丢失具体指哪些类型呢？

Reduck 底层虽然是基于 Redux 实现，但是屏蔽了 Redux 的一些底层概念，如 Reducer。另外，Reduck 对于 model 是动态挂载的，而 Redux 创建 store 的时候，就会传入所有的 reducer。因为这些不同，直接使用 Redux 的一些底层 API，可能获取不到准确的类型提示。

例如：`store.getState()` 无法获取全局 state 的类型。（因为 Reduck 对于 model 是动态挂载的） 

一般建议尽量直接通过 Reduck 的 API 来实现需求，这样可以获得良好的类型信息。
